"""Dynamic Ralph: structured phases and step-based workflow execution."""

from multi_agent.workflow.editing import (
    apply_edits,
    discard_edit_file,
    EditValidationError,
    parse_edit_file,
    remove_edit_file,
    validate_edits,
)
from multi_agent.workflow.executor import AgentResult, execute_step
from multi_agent.workflow.models import (
    AddAfterEdit,
    EditDescriptionEdit,
    EditOperation,
    HistoryEntry,
    NewStepSpec,
    ReorderEdit,
    RestartEdit,
    SkipEdit,
    SplitEdit,
    Step,
    StepStatus,
    StepType,
    StoryStatus,
    StoryWorkflow,
    WorkflowState,
)
from multi_agent.workflow.prompts import compose_step_prompt, STEP_INSTRUCTIONS
from multi_agent.workflow.scratch import (
    append_global_scratch,
    append_story_scratch,
    cleanup_story_scratch,
    read_global_scratch,
    read_story_scratch,
    write_global_scratch,
    write_story_scratch,
)
from multi_agent.workflow.state import (
    find_assignable_story,
    initialize_state_from_prd,
    load_state,
    locked_state,
    save_state,
    validate_dependency_graph,
)
from multi_agent.workflow.steps import (
    create_default_workflow,
    MANDATORY_STEPS,
    MAX_RESTARTS_PER_STEP,
    MAX_STEPS_PER_WORKFLOW,
    STEP_ALLOWS_EDITING,
    STEP_TIMEOUTS,
)


__all__ = [
    'AddAfterEdit',
    'AgentResult',
    'EditDescriptionEdit',
    'EditOperation',
    'EditValidationError',
    'HistoryEntry',
    'MANDATORY_STEPS',
    'MAX_RESTARTS_PER_STEP',
    'MAX_STEPS_PER_WORKFLOW',
    'NewStepSpec',
    'ReorderEdit',
    'RestartEdit',
    'STEP_ALLOWS_EDITING',
    'STEP_INSTRUCTIONS',
    'STEP_TIMEOUTS',
    'SkipEdit',
    'SplitEdit',
    'Step',
    'StepStatus',
    'StepType',
    'StoryStatus',
    'StoryWorkflow',
    'WorkflowState',
    'append_global_scratch',
    'append_story_scratch',
    'apply_edits',
    'cleanup_story_scratch',
    'compose_step_prompt',
    'create_default_workflow',
    'discard_edit_file',
    'execute_step',
    'find_assignable_story',
    'initialize_state_from_prd',
    'load_state',
    'locked_state',
    'parse_edit_file',
    'read_global_scratch',
    'read_story_scratch',
    'remove_edit_file',
    'save_state',
    'validate_dependency_graph',
    'validate_edits',
    'write_global_scratch',
    'write_story_scratch',
]
